services:
  mysql:
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "3306:3306"
    networks:
      - databases
    volumes:
      - ./mysql:/var/lib/mysql
      - ./mysql_scripts:/docker-entrypoint-initdb.d

  phpmyadmin:
     image: phpmyadmin:latest
     restart: always
     depends_on:
       - mysql
     environment:
       PMA_HOST: mysql
       PMA_PORT: 3306
       PMA_USER: ${PMA_USER}
       PMA_PASSWORD: ${PMA_PASSWORD}
     ports:
       - "8090:80"
     networks:
       - databases

  mongodb:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - "27017:27017"
    networks:
      - databases
    volumes:
      - ./mongo:/data/db

  mongo-express:
    image: mongo-express:latest
    restart: always
    depends_on:
        - mongodb
    environment:
        ME_CONFIG_MONGODB_SERVER: mongodb
        ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_INITDB_ROOT_USERNAME}
        ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
        ME_CONFIG_BASICAUTH: false
    ports:
        - "8091:8081"
    networks:
        - databases

  apache:
    build: .
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
      - ./:/app
    depends_on:
      - mysql
    networks:
      - databases
    environment:
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - MONGO_HOST=${MONGO_HOST}
      - MONGO_USERNAME=${MONGO_USERNAME}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
      - MONGO_DATABASE=${MONGO_DATABASE}
    command: >
      sh -c "echo 'ServerName localhost' >> /etc/apache2/apache2.conf &&
             echo '<Directory /var/www/html>
                Options Indexes FollowSymLinks
                AllowOverride All
                Require all granted
             </Directory>' > /etc/apache2/conf-available/custom-permissions.conf &&
             a2enconf custom-permissions &&
             chown -R www-data:www-data /var/www/html &&
             chmod -R 755 /var/www/html &&
             apache2-foreground"

networks:
  databases:
    driver: bridge