services:

  mysql:
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_USER: username
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: mariadb_test_db
    ports:
      - "3306:3306"
    networks:
      - databases
    volumes:
      - ./mysql:/var/lib/mysql
      - ./mysql_scripts:/docker-entrypoint-initdb.d

  phpmyadmin:
     image: phpmyadmin:latest
     restart: always
     depends_on:
       - mysql
     environment:
       PMA_HOST: mysql
       PMA_PORT: 3306
       PMA_USER: root
       PMA_PASSWORD: root_password
     ports:
       - "8090:80"
     networks:
       - databases

  mongodb:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin_username
      MONGO_INITDB_ROOT_PASSWORD: admin_password
    ports:
      - "27017:27017"
    networks:
      - databases
    volumes:
      - ./mongo:/data/db

  mongo-express:
    image: mongo-express:latest
    restart: always
    depends_on:
        - mongodb
    environment:
        ME_CONFIG_MONGODB_SERVER: mongodb
        ME_CONFIG_MONGODB_ADMINUSERNAME: admin_username
        ME_CONFIG_MONGODB_ADMINPASSWORD: admin_password
        ME_CONFIG_BASICAUTH: false
    ports:
        - "8091:8081"
    networks:
        - databases

  apache:
    build: .
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
      - ./:/app
    depends_on:
      - mysql
    networks:
      - databases
    command: >
      sh -c "echo 'ServerName localhost' >> /etc/apache2/apache2.conf &&
             echo '<Directory /var/www/html>
                Options Indexes FollowSymLinks
                AllowOverride All
                Require all granted
             </Directory>' > /etc/apache2/conf-available/custom-permissions.conf &&
             a2enconf custom-permissions &&
             chown -R www-data:www-data /var/www/html &&
             chmod -R 755 /var/www/html &&
             apache2-foreground"

networks:
  databases:
    driver: bridge