services:

  mysql:
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_USER: username
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: mariadb_test_db
    ports:
      - "3306:3306"
    networks:
      - databases
    volumes:
      - ./mysql:/var/lib/mysql
      - ./mysql_scripts:/docker-entrypoint-initdb.d

  phpmyadmin:
     image: phpmyadmin:latest
     restart: always
     depends_on:
       - mysql
     environment:
       PMA_HOST: mysql
       PMA_PORT: 3306
       PMA_USER: root
       PMA_PASSWORD: root_password
     ports:
       - "8090:80"
     networks:
       - databases

  mongodb:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin_username
      MONGO_INITDB_ROOT_PASSWORD: admin_password
    ports:
      - "27017:27017"
    networks:
      - databases
    volumes:
      - ./mongo:/data/db

  mongo-express:
    image: mongo-express:latest
    restart: always
    depends_on:
      - mongodb

  apache:
    image: php:8.2-apache
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./src/public:/var/www/html
      - ./src/templates:/var/www/html/templates
    depends_on:
      - mysql
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin_username
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin_password
      ME_CONFIG_BASICAUTH: false
    networks:
      - databases
    command: sh -c "docker-php-ext-install mysqli && docker-php-ext-enable mysqli && apache2-foreground"

networks:
  databases:
    driver: bridge